### PR TITLE
Fixed beamrate/manual collect bugs, renamed passive to auto, added ma…

### PR DESCRIPTION
**Pull request by KaushikMalapati**
…nual collection indicator

## Description

- Renamed "Passive" mode to "Auto" mode
- Added a boolean pv to show when manual mode is currently collecting
- Fixed a bug that caused the accelerator to always be NC
- Fixed a bug with manual mode that would have caused inconsistent behavior if manual collection was started while in auto mode

## Motivation and Context

Issues noticed during a test over a weekend
https://jira.slac.stanford.edu/browse/ECS-875

## Pre-merge checklist
- [ ] Code works interactively
- [ ] Code contains descriptive comments
- [ ] Test suite passes locally
- [ ] Libraries are set to ``Always Newest`` version (``Library, *``)
- [ ] Committed with ``pre-commit`` or ran ``pre-commit run --all-files``

### CODE REVIEW

**Review by ghalym — APPROVED** [review]
Approve the changes for the eV range. 
The rest pending test on 0.0.0.0

**Comment by tangkong** [comment]
The changes look sensible to me, but I don't think I'm qualified to give the green stamp here.  This effort is being made in conjunction with https://github.com/pcdshub/pcdsdevices/pull/1303 ?

**Comment by KaushikMalapati** [comment]
Yes. https://github.com/pcdshub/pcdsdevices/pull/1303 has cosmetic screen changes, a bug fix, and also uses a new pv that this pr adds. https://github.com/pcdshub/lcls-plc-kfe-rix-motion/pull/75 is also related. The PPM_PowerMeter_IM4K2 function block in it is almost an exact copy of PPM_PowerMeter in cc, but has a custom analoginput for the voltage and a thermocouple instead of a tempsensor, so I am mirroring changes made in this common-components pull request to FB_PPM_PowerMeter_IM4K2

**Review by ZLLentz — APPROVED** [review]
These all make sense to me, the bug fixes look correct and the design changes are good.
I feel bad for not catching some of these on prior review

**Pull request merged**
