### PR TITLE
Atm states

### PR DESCRIPTION
**Pull request by nrwslac**
## Description

- adds two more states to FB_ATM.
- this should be backward compatible since valid bool still needs to be set True.
- 

## Motivation and Context

- TM1K2 needs more states.

## How Has This Been Tested?

- Not tested, I will

## Pre-merge checklist
- [ ] Code works interactively
- [ ] Code contains descriptive comments
- [ ] Test suite passes locally
- [ ] Libraries are set to ``Always Newest`` version (``Library, *``)
- [ ] Committed with ``pre-commit`` or ran ``pre-commit run --all-files``

### CODE REVIEW

**Review by patoppermann — APPROVED** [review]
Thanks, the two new targets have been added.
Looks Good

**Comment by ZLLentz** [comment]
Changing an enum is never backwards compatible, the GUI will pick up the new options which could cause issues

**Review by ZLLentz — CHANGES_REQUESTED** [review]
Can we discuss a better way forward for these?
Currently we've made extra special FBs for ATMs with extra states, which isn't sustainable but at least it's backwards compatible.
More thought is needed before doing something like this.

**Comment by nrwslac** [comment]
other options, copy and paste specialized fb for tm1k2. The other idea was inheritance, but I threw that out because of parent PV concerns.

**Comment by ZLLentz** [comment]
I think, in principle, if this doesn't cause behavioral changes or bugs in existing software, this is ok to do, but I don't _know_ that it won't cause this kind of issue.

I'm really hesitant because we did this differently on the other ATMs
Though maybe at this point we've added states to all the ATMs individually?
Maybe we need to support multiple ATM variants?

Things that might go wrong:
- Extra database loads that fail because the device doesn't have an entry in the pmpsdb for the extra states
- Unexplored exceptions in the typhos screen
- Extra options in the typhos screen that TMO complains to Tong about

Controls wise on the PLC it's probably no big deal

I'm going to remove my change request because that's mean if I'm going away on vacay and please test this before deploying it wildly

**Review by ZLLentz — COMMENTED** [review]
Removing my request changes marker

**Comment by nrwslac** [comment]
The hutch explored local solutions instead of this.

**Pull request closed without merging**
